[package]
name = "eth-client"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk-pure = {git = "https://github.com/snjax/near-sdk-pure-rs", branch="main", default-features = false}
eth-types =  { path = "../eth-types" }
rlp = {version = "0.4.2", default-features=false}
ethash = { git = "https://github.com/nearprotocol/rust-ethash", branch = "upgrade-eth-types", default-features = false}
# hex = "0.4.0"
# rustc-hex = "2.1.0"


[features]
default = []
expensive_tests = []
